name: s2 test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: use deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: test s2
        run: deno test
