name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: use deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: test
        run: deno test test/
